---
title: "Allison, Shakira, and Gracie Final Stat 345 Project"
output: word_document
date: "2025-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section One (Allison with songs)

```{r student1}
##songs listed in word document 
```


## Section Two (Gracie with year and time/word length)

```{r student2}

```

## Section Three (Shakira with lyrics)

```{r student3}
#Data for all the songs
songs_data <- tibble(
  Title = c(
    "He'll Have to Go", "El Paso", "Sink the Bismarck", "Please Help Me, I'm Falling", "Let's Think About Living",
    "Something's Burning", "Snowbird", "The Wonder of You", "It's Only Make Believe", "Coward of the County",
    "Don't Fall in Love with a Dreamer", "Stand by Me", "Drivin' My Life Away", "You Decorated My Life", "In America",
    "Blaze of Glory", "Just Between You and Me", "Free Fallin'", "Breathe", "Amazed", "The Way You Love Me", "I Need You",
    "That's the Way", "Yes!", "The Best Day", "How Do You Like Me Now?!", "My Best Friend", "I Hope You Dance",
    "What About Now", "Cowboy Take Me Away", "Need You Now", "Mine", "You Belong with Me", "Stuck Like Glue", "Undo It",
    "The House That Built Me", "If I Die Young", "American Honey", "Lover, Lover", "The Bones", "I Hope", "10,000 Hours",
    "Chasin' You", "Nobody but You", "One Man Band", "Got What I Got", "Die from a Broken Heart", "One of Them Girls",
    "Hard to Forget", "One Margarita", "I Hope You're Happy Now", "Even Though I'm Leaving", "Be Like That", "Homesick",
    "Bluebird", "Does to Me", "More Than My Hometown", "Lovin' on You"
  ),
  Artist = c(
    "Jim Reeves", "Marty Robbins", "Johnny Horton", "Hank Locklin", "Bob Luman", "Kenny Rogers & The First Edition",
    "Anne Murray", "Elvis Presley", "Glen Campbell", "Kenny Rogers", "Kenny Rogers & Kim Carnes", "Mickey Gilley",
    "Eddie Rabbitt", "Kenny Rogers", "Charlie Daniels Band", "Jon Bon Jovi", "Lou Gramm", "Tom Petty", "Faith Hill",
    "Lonestar", "Faith Hill", "LeAnn Rimes", "Jo Dee Messina", "Chad Brock", "George Strait", "Toby Keith", "Tim McGraw",
    "Lee Ann Womack with Sons of the Desert", "Lonestar", "Dixie Chicks", "Lady Antebellum", "Taylor Swift", "Taylor Swift",
    "Sugarland", "Carrie Underwood", "Miranda Lambert", "The Band Perry", "Lady Antebellum", "Jerrod Niemann", "Maren Morris",
    "Gabby Barrett featuring Charlie Puth", "Dan + Shay and Justin Bieber", "Morgan Wallen", "Blake Shelton and Gwen Stefani",
    "Old Dominion", "Jason Aldean", "Maddie & Tae", "Lee Brice", "Sam Hunt", "Luke Bryan", "Carly Pearce and Lee Brice",
    "Luke Combs", "Kane Brown, Swae Lee and Khalid", "Kane Brown", "Miranda Lambert", "Luke Combs featuring Eric Church",
    "Morgan Wallen", "Luke Combs"
  ),
  Year = c(
    1959, 1959, 1960, 1960, 1960, 1970, 1970, 1970, 1970, 1979, 1980, 1980, 1980, 1979, 1980, 1990, 1989, 1989, 1999, 1999,
    2000, 2000, 2000, 2000, 2000, 1999, 1999, 2000, 2000, 1999, 2009, 2010, 2008, 2010, 2010, 2010, 2010, 2010, 2010, 2019,
    2020, 2019, 2019, 2019, 2020, 2020, 2019, 2020, 2020, 2020, 2019, 2019, 2020, 2019, 2019, 2020, 2020, 2020
  ),
  Song_Length_Seconds = c(
    140, 278, 194, 141, 122, 245, 128, 159, 145, 260, 219, 216, 197, 218, 201, 335, 296, 254, 249, 240, 187, 228, 200, 203,
    200, 210, 279, 294, 212, 287, 277, 230, 232, 247, 177, 236, 223, 224, 198, 197, 210, 167, 205, 195, 188, 198, 223, 178,
    193, 199, 225, 190, 205, 209, 223, 217, 195, 205
  ),
  Word_Count = c(
    152, 466, 430, 114, 281, 191, 220, 116, 165, 419, 213, 154, 252, 161, 295, 368, 271, 176, 254, 256, 306, 198, 467, 262,
    285, 289, 312, 318, 298, 247, 260, 406, 396, 558, 381, 297, 359, 216, 361, 326, 470, 304, 323, 213, 315, 261, 294, 365,
    409, 311, 224, 340, 450, 276, 308, 384, 424, 223
  ),
url = c(
  "https://genius.com/Jim-reeves-hell-have-to-go-lyrics",
  "https://genius.com/Marty-robbins-el-paso-lyrics",
  "https://genius.com/Johnny-horton-sink-the-bismarck-lyrics",
  "https://genius.com/Hank-locklin-please-help-me-im-falling-lyrics",
  "https://genius.com/Bob-luman-lets-think-about-living-lyrics",
  "https://genius.com/Kenny-rogers-and-the-first-edition-somethings-burning-lyrics",
  "https://genius.com/Anne-murray-snowbird-lyrics",
  "https://genius.com/Elvis-presley-the-wonder-of-you-lyrics",
  "https://genius.com/Glen-campbell-its-only-make-believe-lyrics",
  "https://genius.com/Kenny-rogers-coward-of-the-county-lyrics",
  "https://genius.com/Kenny-rogers-dont-fall-in-love-with-a-dreamer-lyrics",
  "https://genius.com/Mickey-gilley-stand-by-me-lyrics",
  "https://genius.com/Eddie-rabbitt-drivin-my-life-away-lyrics",
  "https://genius.com/Kenny-rogers-you-decorated-my-life-lyrics",
  "https://genius.com/Charlie-daniels-band-in-america-lyrics",
  "https://genius.com/Bon-jovi-blaze-of-glory-lyrics",
  "https://genius.com/Lou-gramm-just-between-you-and-me-lyrics",
  "https://genius.com/Tom-petty-free-fallin-lyrics",
  "https://genius.com/Faith-hill-breathe-lyrics",
  "https://genius.com/Lonestar-amazed-lyrics",
  "https://genius.com/Faith-hill-the-way-you-love-me-lyrics",
  "https://genius.com/Leann-rimes-i-need-you-lyrics",
  "https://genius.com/Jo-dee-messina-thats-the-way-lyrics",
  "https://genius.com/Chad-brock-yes-lyrics",
  "https://genius.com/George-strait-the-best-day-lyrics",
  "https://genius.com/Toby-keith-how-do-you-like-me-now-lyrics",
  "https://genius.com/Tim-mcgraw-my-best-friend-lyrics",
  "https://genius.com/Lee-ann-womack-i-hope-you-dance-lyrics",
  "https://genius.com/Lonestar-what-about-now-lyrics",
  "https://genius.com/Dixie-chicks-cowboy-take-me-away-lyrics",
  "https://genius.com/Lady-antebellum-need-you-now-lyrics",
  "https://genius.com/Taylor-swift-mine-lyrics",
  "https://genius.com/Taylor-swift-you-belong-with-me-lyrics",
  "https://genius.com/Sugarland-stuck-like-glue-lyrics",
  "https://genius.com/Carrie-underwood-undo-it-lyrics",
  "https://genius.com/Miranda-lambert-the-house-that-built-me-lyrics",
  "https://genius.com/The-band-perry-if-i-die-young-lyrics",
  "https://genius.com/Lady-antebellum-american-honey-lyrics",
  "https://genius.com/Jerrod-niemann-lover-lover-lyrics",
  "https://genius.com/Maren-morris-the-bones-lyrics",
  "https://genius.com/Gabby-barrett-i-hope-lyrics",
  "https://genius.com/Dan-shay-and-justin-bieber-10000-hours-lyrics",
  "https://genius.com/Morgan-wallen-chasin-you-lyrics",
  "https://genius.com/Blake-shelton-and-gwen-stefani-nobody-but-you-lyrics",
  "https://genius.com/Old-dominion-one-man-band-lyrics",
  "https://genius.com/Jason-aldean-got-what-i-got-lyrics",
  "https://genius.com/Maddie-and-tae-die-from-a-broken-heart-lyrics",
  "https://genius.com/Lee-brice-one-of-them-girls-lyrics",
  "https://genius.com/Sam-hunt-hard-to-forget-lyrics",
  "https://genius.com/Luke-bryan-one-margarita-lyrics",
  "https://genius.com/Carly-pearce-and-lee-brice-i-hope-youre-happy-now-lyrics",
  "https://genius.com/Luke-combs-even-though-im-leaving-lyrics",
  "https://genius.com/Kane-brown-swae-lee-and-khalid-be-like-that-lyrics",
  "https://genius.com/Kane-brown-homesick-lyrics",
  "https://genius.com/Miranda-lambert-bluebird-lyrics",
  "https://genius.com/Luke-combs-and-eric-church-does-to-me-lyrics",
  "https://genius.com/Morgan-wallen-more-than-my-hometown-lyrics",
  "https://genius.com/Luke-combs-lovin-on-you-lyrics"
))
print(songs_data)
```

```{r}

library(dplyr)
library(rvest)
library(stringr)
library(purrr)

# Updated lyrics scraper with latest selector
get_lyrics_genius <- function(url) {
  tryCatch({
    h <- read_html(url)
    lyrics <- html_nodes(h, 'div[data-lyrics-container="true"]') %>%
      html_text2()
    full_lyrics <- paste(lyrics, collapse = " ")
    list(
      words = str_split(full_lyrics, "\\s+")[[1]],
      text = full_lyrics
    )
  }, error = function(e) {
    warning("Failed to scrape: ", url)
    return(list(words = NA, text = NA))
  })
}

# Add row_id to track songs
songs_data <- songs_data %>%
  mutate(row_id = row_number())

# Pull lyrics safely
lyrics_df <- songs_data %>%
  rowwise() %>%
  mutate(
    lyrics_data = list(get_lyrics_genius(url)),
    words = list(lyrics_data$words),         # wrap in list()
    full_text = lyrics_data$text,
    word_count = if (!is.na(lyrics_data$words[1])) length(lyrics_data$words) else NA
  ) %>%
  ungroup() %>%
  select(row_id, words, full_text, word_count)

# Join lyrics back to main data
songs_df_with_lyrics <- songs_data %>%
  left_join(lyrics_df, by = "row_id") %>%
  select(-row_id)

# Take a peek!
print(songs_df_with_lyrics)

```


## Section Four (Working together on function)

```{r student4}
#going to have to create lists like this (i got this from chatgpt)
#maybe we do a different list for each decade 
songs <- list(
  list(title = "Hello", lyrics = "Hello, it's me. I was wondering if after all these years you'd like to meet."),
  list(title = "Shake It Off", lyrics = "Cause the players gonna play, play, play, play, play. And the haters gonna hate, hate, hate, hate, hate."),
  list(title = "Happy", lyrics = "Because I'm happy. Clap along if you feel like a room without a roof. Because I'm happy.")
)

#then write a function that can run through this list 


#possible function looking for titles
measure_title_repetition <- function(lyrics, title) {
  # Normalize text
  lyrics_clean <- tolower(gsub("[[:punct:]]", "", lyrics))
  title_clean <- tolower(gsub("[[:punct:]]", "", title))
  
  words <- unlist(strsplit(lyrics_clean, "\\s+"))
  title_words <- unlist(strsplit(title_clean, "\\s+"))
  
  title_length <- length(title_words)
  if (length(words) < title_length) return(0)
  
  # Slide through lyrics to match title
  matches <- 0
  for (i in 1:(length(words) - title_length + 1)) {
    if (all(words[i:(i + title_length - 1)] == title_words)) {
      matches <- matches + 1
    }
  }
  
  # Return matches normalized by total number of phrases in lyrics
  return(matches / (length(words) - title_length + 1))
}




#how to get the results of how many songs repeat their title
results <- lapply(songs, function(song) {
  list(
    title = song$title,
    title_rep = measure_title_repetition(song$lyrics, song$title)
  )
})

# Show results
print(results)


```